import type { SkillManifest } from "./definition.js";

const skill = (id: string, name: string, desc: string, riskLevel: SkillManifest["riskLevel"], runtimeType: SkillManifest["runtimeType"], perms: SkillManifest["permissions"], input: Record<string, { type: string; required: boolean }>, output: Record<string, { type: string }>): SkillManifest => ({
  id, name, provider: "zhixu", version: "1.0.0", description: desc, permissions: perms, riskLevel, runtimeType, inputSchema: input, outputSchema: output
});

const r0 = (scope: string, desc: string): SkillManifest["permissions"][0] => ({ scope, description: desc, riskLevel: "L0" as const, defaultGranted: true });
const r1 = (scope: string, desc: string, granted = false): SkillManifest["permissions"][0] => ({ scope, description: desc, riskLevel: "L1" as const, defaultGranted: granted });
const r2 = (scope: string, desc: string, granted = false): SkillManifest["permissions"][0] => ({ scope, description: desc, riskLevel: "L2" as const, defaultGranted: granted });

export const BUILTIN_SKILLS: SkillManifest[] = [
  skill("skill_source_parse", "source.parse", "Parse project-scoped sources into document nodes and evidence anchors.", "L1", "native", [r1("read_project_source", "Read source files", true), r1("write_project_index", "Write parsed index", true)], { sourceId: { type: "string", required: true } }, { document: { type: "object" }, evidenceAnchors: { type: "array" } }),
  skill("skill_artifact_verify", "artifact.verify", "Verify artifact blocks for evidence coverage, responsibility color and risk.", "L2", "workflow", [r1("read_project_artifact", "Read artifact data", true), r2("read_project_evidence", "Read evidence records")], { artifactId: { type: "string", required: true }, blockId: { type: "string", required: true } }, { verdict: { type: "string" }, evidenceCoverage: { type: "number" } }),
  skill("skill_memory_reflect", "memory.reflect", "Extract reusable knowledge capsule candidates after project completion.", "L2", "workflow", [r1("read_project_summary", "Read project summary", true), r2("write_memory_candidate", "Write memory candidates")], { projectId: { type: "string", required: true } }, { capsule: { type: "object" } }),
  skill("skill_ppt_generate", "ppt.generate", "Generate PPTX presentations with ZhiXu brand theme and evidence notes.", "L2", "native", [r1("read_project_artifact", "Read artifact data for slides", true), r2("write_project_export", "Write export file")], { artifactId: { type: "string", required: true } }, { fileBuffer: { type: "Buffer" }, mimeType: { type: "string" } }),
  skill("skill_docx_generate", "docx.generate", "Generate DOCX documents with structured sections and evidence markers.", "L2", "native", [r1("read_project_artifact", "Read artifact data for document", true), r2("write_project_export", "Write export file")], { artifactId: { type: "string", required: true } }, { fileBuffer: { type: "Buffer" }, mimeType: { type: "string" } }),
  skill("skill_task_breakdown", "task.breakdown", "Break down complex tasks into structured sub-tasks with risk assessment.", "L1", "workflow", [r1("read_project_tasks", "Read project tasks", true), r1("write_project_tasks", "Write sub-tasks", true)], { taskTitle: { type: "string", required: true } }, { subTasks: { type: "array" } }),
  skill("skill_progress_tracking", "progress.track", "Track project progress and detect stalled or at-risk tasks.", "L0", "native", [r1("read_project_tasks", "Read project tasks", true)], { projectId: { type: "string", required: true } }, { progress: { type: "number" }, risks: { type: "array" } }),
  skill("skill_pdf_parse", "pdf.parse", "Parse PDF documents into structured content with OCR support.", "L1", "native", [r1("read_project_source", "Read source PDF", true), r1("write_project_index", "Write parsed content", true)], { sourceId: { type: "string", required: true } }, { document: { type: "object" }, pages: { type: "number" } }),
  skill("skill_ocr", "ocr.process", "Run OCR on image-based documents to extract text content.", "L1", "native", [r1("read_project_source", "Read source images", true), r1("write_project_index", "Write OCR results", true)], { sourceId: { type: "string", required: true } }, { text: { type: "string" }, confidence: { type: "number" } }),
  skill("skill_excel_data", "excel.process", "Extract and analyze data from Excel spreadsheets.", "L1", "native", [r1("read_project_source", "Read source Excel", true), r1("write_project_index", "Write extracted data", true)], { sourceId: { type: "string", required: true } }, { sheets: { type: "array" }, summary: { type: "object" } }),
  skill("skill_literature_search", "literature.search", "Search academic databases for relevant papers and references.", "L1", "external_api", [r1("read_project", "Read project context", true), r2("external_api_call", "Call external search API")], { query: { type: "string", required: true }, maxResults: { type: "number", required: false } }, { papers: { type: "array" }, totalFound: { type: "number" } }),
  skill("skill_citation_check", "citation.check", "Verify citation format, completeness and detect fabricated references.", "L0", "workflow", [r1("read_project_artifact", "Read artifact citations", true)], { artifactId: { type: "string", required: true } }, { verified: { type: "number" }, issues: { type: "array" } }),
  skill("skill_calendar_reminder", "calendar.remind", "Manage project deadlines and send reminder notifications.", "L0", "native", [r1("read_project", "Read project deadlines", true)], { projectId: { type: "string", required: true } }, { upcoming: { type: "array" } }),
  skill("skill_exam_coach", "exam.coach", "Generate review plans and practice questions for exam preparation.", "L1", "workflow", [r1("read_project", "Read project context", true), r1("write_project_artifact", "Write practice questions", true)], { projectId: { type: "string", required: true }, examDate: { type: "string", required: true } }, { plan: { type: "object" }, questions: { type: "array" } }),
  skill("skill_presentation_coach", "presentation.coach", "Coach presentation delivery with timing and slide optimization.", "L1", "workflow", [r1("read_project_artifact", "Read presentation slides", true)], { artifactId: { type: "string", required: true } }, { feedback: { type: "array" }, timingEstimate: { type: "number" } }),
  skill("skill_experiment_log", "experiment.log", "Structure and standardize experiment logs with variable tracking.", "L1", "workflow", [r1("read_project", "Read project context", true), r1("write_project_artifact", "Write experiment log", true)], { projectId: { type: "string", required: true } }, { log: { type: "object" } }),
  skill("skill_image_process", "image.process", "Process and annotate images for academic documents.", "L1", "native", [r1("read_project_source", "Read source images", true), r1("write_project_artifact", "Write processed images", true)], { sourceId: { type: "string", required: true }, operation: { type: "string", required: true } }, { result: { type: "object" } }),
  skill("skill_diagram_generate", "diagram.generate", "Generate diagrams, flowcharts and visual aids for academic content.", "L1", "native", [r1("read_project", "Read project context", true), r1("write_project_artifact", "Write diagram artifacts", true)], { type: { type: "string", required: true }, description: { type: "string", required: true } }, { diagram: { type: "object" }, format: { type: "string" } }),
  skill("skill_github_repo", "github.repo", "Connect to GitHub repositories for code-related project tasks.", "L2", "external_api", [r1("read_project", "Read project context", true), r2("external_api_call", "Call GitHub API")], { repoUrl: { type: "string", required: true } }, { repo: { type: "object" } }),
  skill("skill_web_research", "web.research", "Search the web for information and synthesize findings.", "L1", "external_api", [r1("read_project", "Read project context", true), r2("external_api_call", "Call web search API")], { query: { type: "string", required: true } }, { results: { type: "array" }, summary: { type: "string" } }),
  skill("skill_translation", "translate", "Translate content between languages with academic terminology support.", "L0", "external_api", [r1("read_project_artifact", "Read artifact content", true), r1("write_project_artifact", "Write translated content", true)], { text: { type: "string", required: true }, targetLang: { type: "string", required: true } }, { translated: { type: "string" } }),
  skill("skill_style_unifier", "style.unify", "Unify writing style across document sections per user preferences.", "L0", "workflow", [r1("read_project_artifact", "Read artifact content", true), r1("write_project_artifact", "Write styled content", true)], { artifactId: { type: "string", required: true } }, { changes: { type: "number" }, consistency: { type: "number" } }),
  skill("skill_knowledge_capsule", "knowledge.capsule", "Create and manage reusable knowledge capsules from completed projects.", "L0", "workflow", [r1("read_project", "Read project summary", true), r1("write_project_capsule", "Write knowledge capsule", true)], { projectId: { type: "string", required: true } }, { capsule: { type: "object" } }),
  skill("skill_mentor_feedback", "mentor.feedback", "Parse and structure mentor feedback into actionable improvement items.", "L1", "workflow", [r1("read_project", "Read project context", true), r1("write_project_artifact", "Write feedback items", true)], { projectId: { type: "string", required: true }, rawContent: { type: "string", required: true } }, { items: { type: "array" } }),
  skill("skill_review_response", "review.response", "Draft structured responses to peer review or mentor feedback.", "L1", "workflow", [r1("read:project.artifacts", "Read project artifacts for context", true), r1("write:project.artifacts", "Write response artifacts")], { feedbackId: { type: "string", required: true } }, { response: { type: "object" } }),
  skill("skill_grant_application", "grant.application", "Generate structured grant application drafts from project data.", "L1", "workflow", [r1("read:project.artifacts", "Read project artifacts for grant content", true), r1("write:project.artifacts", "Write grant application artifacts")], { projectId: { type: "string", required: true } }, { application: { type: "object" } }),
  skill("skill_academic_resume", "academic.resume", "Generate academic CV and resume from user profile and project history.", "L0", "workflow", [r0("read:user.profile", "Read user profile data"), r0("write:project.artifacts", "Write resume artifact")], { userId: { type: "string", required: true } }, { resume: { type: "object" } }),
  skill("skill_group_collaboration", "group.collaboration", "Coordinate task assignment and progress across group members.", "L1", "workflow", [r1("read:project.tasks", "Read project tasks for coordination", true), r1("write:project.tasks", "Write task assignments")], { projectId: { type: "string", required: true } }, { assignments: { type: "array" } }),
  skill("skill_plagiarism_precheck", "plagiarism.precheck", "Pre-check artifacts for potential plagiarism risk before submission.", "L0", "workflow", [r0("read:project.artifacts", "Read project artifacts for plagiarism check")], { artifactId: { type: "string", required: true } }, { riskScore: { type: "number" }, flaggedSections: { type: "array" } }),
  skill("skill_offline_cache", "offline.cache", "Cache project data locally for offline access and synchronization.", "L0", "local_only", [r0("read:project", "Read project data for caching"), r0("write:local.cache", "Write to local cache storage")], { projectId: { type: "string", required: true } }, { cachedAt: { type: "string" }, sizeBytes: { type: "number" } }),
  skill("skill_termbase", "termbase", "Manage and query workspace terminology databases for consistent usage.", "L0", "native", [r0("read:workspace.termbase", "Read workspace terminology"), r0("write:workspace.termbase", "Write terminology entries")], { term: { type: "string", required: false }, operation: { type: "string", required: true } }, { entries: { type: "array" } })
];
